Homework 05
badimalex/go-course pull request #4
Opened 2023-07-18 14:38 UTC by badimalex

2023-07-25 07:00 UTC, DmitriyVTitov requested changes
1. Паники не подойдут. Паника - крайнее средство, а у вас она по любому поводу.
2. Код в main() следует разделить на отдельные функции (почитайте про "выделение метода").

2023-07-26 09:18 UTC, badimalex commented
есть несколько вопросов
- нормально ли что я использую log.Fatalf для ошибок?
- мне не нравится участок кода с 28 по 48; Просится упаковать в функцию loadData и чтобы data := loadData
чтобы не было всей это логики. Но тогда нарушается задание, так как там нужно чтобы 
>Механизм должен использовать io.Writer в
>В процессе обязательно должен использоваться io.Reader.
А если я это засуну в функцию то в качестве параметра передавать уже будет нечего, так как все будет делаться там внутри.
Может сделать пакет storage? Вообще как посоветуете отрефакторить этот участок кода? Может подсказку дадите. 
@DmitriyVTitov

2023-07-29 09:45 UTC, DmitriyVTitov approved these changes
Да, вполне неплохо. Читается и понимается достаточно легко.

2023-07-29 09:45 UTC, DmitriyVTitov commented on homework-05/cmd/gosearch/gosearh.go
> +	}
Мы не должны перезаписывать файл, если смогли прочитать данные из него.

2023-07-29 14:01 UTC, merged